services:
  nginx:
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 256M
    image: nginx
    ports:
    - 8080:80
  redis:
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 256M
    image: redis
    ports:
    - 9000:90
version: '3.8'
