services:
  nginx:
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 128M
    image: nginx
    ports:
    - 80:80
    restart: on-failure
  redis:
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 128M
    image: redis
    ports:
    - 6379:6379
  web:
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 256M
    image: node
    ports:
    - 81:5000
    restart: on-failure
version: '3.8'
