services:
  nginx:
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 128M
    environment:
      DB: '50'
    healthcheck:
      interval: 1m
      retries: 3
      start_period: 30s
      test:
      - CMD
      - curl
      - -f
      - ''
      timeout: 10s
    image: nginx
    ports:
    - 8080:80
    restart: always
version: '3.8'
