services:
  ms1:
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: 2
          memory: 512
    environment:
    - DB=50
    image: nginx
    ports:
    - 8080:80
    - '8080:50'
    restart: always
version: '3'
